### ISSUE TITLE
vue binding expression cannot be translated

### ISSUE THREAD

**Issue by softboy99** [intlify/vue-i18n-next#241] opened 2020-12-18 07:39 UTC
the following editor-options cannot be translated:      
`<dx-item
        data-field="rememberMe"
        editor-type="dxCheckBox"
        :editor-options="{ text: `$t('login_form.Remember_me')`, elementAttr: { class: 'form-text' } }"
 >`

**Comment by kazupon** [comment] 2021-01-21 16:48
I could not reproduce vue binding expression issue.
This is not  vue-i18n issue, so close it.

If you can resolve this issue, you can open a new issue with minimum  reproduction codes and error message.

**Closed by kazupon** 2021-01-21 16:48 UTC
