### ISSUE TITLE
"deepCopy" is not exported by @intlify/shared

### ISSUE THREAD

**Issue by ALABOET** [intlify/vue-i18n-next#1637] opened 2023-11-17 09:17 UTC
### Reporting a bug?

After yesterday's pull request https://github.com/intlify/vue-i18n-next/pull/1635 i started getting an error 
```bash 
Nuxt Build Error: "deepCopy" is not exported by "node_modules/@intlify/shared/dist/shared.mjs", imported by "node_modules/vue-i18n/dist/vue-i18n.mjs".
```

Before it everything worked fine.

### Expected behavior

There should be no errors

### Reproduction

Install latest version of vue-i18n

### System Info

```shell
System:
    OS: Windows 11 10.0.22000
    CPU: (28) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    Memory: 20.00 GB / 31.85 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: master_preferences
    Edge: Chromium (111.0.1661.62)
    Internet Explorer: 11.0.22000.120
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by ALABOET** [comment] 2023-11-17 09:40
```{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/eslint-config-typescript": "^12.1.0",
    "@nuxtjs/i18n": "8.0.0-rc.4",
    "@typescript-eslint/parser": "^6.7.5",
    "eslint": "^8.51.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.1",
    "nuxt": "^3.7.4",
    "prettier": "^3.0.3",
    "sass": "^1.68.0",
    "typescript": "^5.2.2",
    "vite-plugin-vuetify": "^1.0.2",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@mdi/font": "^7.3.67",
    "@nuxtjs/device": "^3.1.1",
    "@pinia/nuxt": "^0.5.1",
    "@popperjs/core": "^2.11.8",
    "@tanstack/vue-query": "^4.37.0",
    "@types/lodash-es": "^4.17.10",
    "@vee-validate/rules": "^4.11.8",
    "axios": "^1.5.1",
    "body-scroll-lock": "^4.0.0-beta.0",
    "dayjs": "^1.11.10",
    "fuse.js": "^6.6.2",
    "imask": "^7.1.3",
    "lodash-es": "^4.17.21",
    "pinia": "^2.1.7",
    "primevue": "^3.36.0",
    "tiny-emitter": "^2.1.0",
    "vee-validate": "^4.11.7",
    "vue-i18n": "^9.5.0",
    "vue3-circle-progress": "^1.0.7"
  }
}

**Comment by BobbieGoede** [comment] 2023-11-17 09:46
Removing the `package-lock.json` file and running `npm install` may fix your issue and/or updating `vue-i18n` to `^9.7.0`. What is the output of `npm why @intlify/shared`?

**Comment by ALABOET** [comment] 2023-11-17 09:59
Output of `yarn why @intlify/shared`
```bash
[1/4] Why do we have the module "@intlify/shared"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@intlify/shared@9.7.0"
info Has been hoisted to "@intlify/shared"
info Reasons this module exists
   - Hoisted from "@intlify#message-compiler#@intlify#shared"
   - Hoisted from "vue-i18n#@intlify#shared"
   - Hoisted from "vue-i18n#@intlify#core-base#@intlify#shared"
   - Hoisted from "@nuxtjs#i18n#@intlify#unplugin-vue-i18n#@intlify#shared"
   - Hoisted from "@nuxtjs#i18n#vue-i18n-routing#@intlify#shared"
   - Hoisted from "@nuxtjs#i18n#@intlify#unplugin-vue-i18n#@intlify#bundle-utils#@intlify#shared"
info Disk size without dependencies: "88KB"
info Disk size with unique dependencies: "88KB"
info Disk size with transitive dependencies: "88KB"
info Number of shared dependencies: 0
=> Found "@nuxtjs/i18n#@intlify/shared@9.5.0"
info Reasons this module exists
   - "@nuxtjs#i18n" depends on it
   - Hoisted from "@nuxtjs#i18n#vue-i18n#@intlify#shared"
   - Hoisted from "@nuxtjs#i18n#vue-i18n#@intlify#core-base#@intlify#shared"
   - Hoisted from "@nuxtjs#i18n#vue-i18n#@intlify#core-base#@intlify#message-compiler#@intlify#shared"
info Disk size without dependencies: "72KB"
info Disk size with unique dependencies: "72KB"
info Disk size with transitive dependencies: "72KB"
info Number of shared dependencies: 0
```

**Comment by BobbieGoede** [comment] 2023-11-17 11:12
This issue is caused by `@nuxtjs/18n@8.0.0-rc.4` having `@intlify/shared` pinned to `9.5.0`, installing the latest edge release of `@nuxtjs/i18n` will likely fix this issue. 

If this is not an option, you may be able to fix this by overriding the `@intlify/shared` version by adding this to your `package.json` file:

```json
  "resolutions": {
    "@intlify/shared": "^9.7.0",
  }
```

I cannot confirm myself this without a minimal reproduction.

**Comment by sampullman** [comment] 2023-11-24 10:15
I am running into this as well after updating to 9.7.0 (along with a few other package updates).

We use PNPM, and the issue persists after pinning to 9.7.0 and a clean repo install. Unfortunately it's not possible to provide a minimal reproduction. It's very strange though, I can verify that there is no other `@intlify/shared` version in `node_modules`, and `deepCopy` is clearly exported in `shared.mjs`.

**Comment by BobbieGoede** [comment] 2023-11-24 10:21
Could you maybe fork a starter project, replace the package and lockfiles with your own, and see if this reproduces this issue? That would be a sufficient minimal reproduction if you could share this, this is very likely a dependency mismatch.

**Comment by sampullman** [comment] 2023-11-26 16:25
I've since switched to `petite-vue-i18n` since we weren't using many advanced features.

I just took the package/lockfile from the broken commit and dropped them in a starter project and there is no build error, which is odd. Definitely a dependency mismatch, but we inspected the lockfile pretty closely and couldn't figure it out.

**Comment by SteinRobert** [comment] 2023-12-11 15:39
Yep, tried that. I'll check whether I can reproduce it again and provide you with a lockfile.

**Comment by 1CoolUsername** [comment] 2023-12-15 15:09
I have the same thing going for me in a Vitesse-ssg Fork. Will provide a solution if found for pnpm builds via git actions. I have one project that is building without that issue, will pinpoint it as it blocks my production flow.

**Comment by 1CoolUsername** [comment] 2023-12-15 16:27
> This issue is caused by `@nuxtjs/18n@8.0.0-rc.4` having `@intlify/shared` pinned to `9.5.0`, installing the latest edge release of `@nuxtjs/i18n` will likely fix this issue.
> 
> If this is not an option, you may be able to fix this by overriding the `@intlify/shared` version by adding this to your `package.json` file:
> 
> ```json
>   "resolutions": {
>     "@intlify/shared": "^9.7.0",
>   }
> ```
> 
> I cannot confirm myself this without a minimal reproduction.

I can confirm my build resolved via remote action with this change. Also mentioned at the below issue.
https://github.com/nuxt-modules/i18n/issues/2569#issuecomment-1827051201

**Comment by kazupon** [comment] 2024-02-28 10:58
close (already fixed latest version)

**Closed by kazupon** 2024-02-28 10:58 UTC
