### ISSUE TITLE
$t() doesn't work on local scope

### ISSUE THREAD

**Issue by luca-smartpricing** [intlify/vue-i18n-next#1446] opened 2023-06-30 09:44 UTC
### Reporting a bug?

As you said [here](https://vue-i18n.intlify.dev/guide/advanced/sfc.html#basic-usage) you can use `$t('hello')` with `i18n` custom block.
_"The locale messages defined by i18n custom blocks, are used as the local scope in single file components. If $t('hello') is used in the template, the hello key defined by i18n custom blocks is referred to."_

### Expected behavior

$t('hello') interpolate `"hello world!"`

### Reproduction

https://stackblitz.com/edit/github-9j4ub2-fee4rr?file=pages%2Findex.vue

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 74.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 3.5.0 - /opt/homebrew/opt/node@18/bin/yarn
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

### Screenshot

<img width="419" alt="Screenshot 2023-06-30 alle 11 43 07" src="https://github.com/intlify/vue-i18n-next/assets/115626063/891c33a9-72e5-40dc-8b70-e25b21ee7917">

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by semiaddict** [comment] 2023-07-10 12:58
Possibly a duplicate of #1186.

**Comment by kazupon** [comment] 2023-07-28 06:32
Thank your for your feedback.

`$t` does not support local scope, only global scope.

Thanks!

**Closed by kazupon** 2023-07-28 06:32 UTC
