### ISSUE TITLE
Uncaught (in promise) TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '__v_emitter' which is either non-existent or configurable in the proxy target

### ISSUE THREAD

**Issue by elboukhari** [intlify/vue-i18n-next#909] opened 2022-01-28 09:31 UTC
Still having this bug

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 15.93 GB / 31.34 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.18362.1593.0)
    Internet Explorer: 11.0.18362.1766
  npmPackages:
    @vitejs/plugin-vue: ^1.9.0 => 1.10.2
    @vue/cli-plugin-babel: 5.0.0-beta.7 => 5.0.0-beta.7
    @vue/cli-service: 5.0.0-beta.7 => 5.0.0-beta.7
    @vue/eslint-config-prettier: 6.0.0 => 6.0.0
    @vue/eslint-config-typescript: 9.1.0 => 9.1.0
    @vuetify/nightly:  3.0.0-next-20220126.0
    vite: ^2.7.13 => 2.7.13
    vue: ^3.2.29 => 3.2.29
    vue-i18n: ^9.2.0-beta.30 => 9.2.0-beta.30
    vue-router: ^4.0.12 => 4.0.12
```

Here is the textual version from console js :
`shared.esm-bundler.js:493 Uncaught (in promise) TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '__v_emitter' which is either non-existent or configurable in the proxy target
    at Proxy.hasOwnProperty (<anonymous>)
    at hasOwn (shared.esm-bundler.js:493:45)
    at Object.set (runtime-core.esm-bundler.js:6762:41)
    at Proxy.mounted (vue-i18n.esm-bundler.js:2003:39)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2667:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:356:32)
    at flushJobs (runtime-core.esm-bundler.js:401:9)`

![image](https://user-images.githubusercontent.com/36670922/151502150-603abfa2-9334-4001-a6d9-fa6d1921abd8.png)

**Comment by kazupon** [comment] 2022-01-28 10:48
Thank you for your reporting!

Unfortunately, I could not reproduce this issue.
vue-i18n-next GitHub issue guideline says:

>Please provide a link to a repo that can reproduce the problem you ran into. A reproduction is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "Status: Need More Info" label. If no reproduction is provided after 5 days, it will be closed.

We need minimum reproduction repo.
Could you give us it, please?

**Comment by elboukhari** [comment] 2022-02-02 18:31
It's with vuetify 3/Vue 3 /vite project.. not simple to give you a repo :(

**Comment by kazupon** [comment] 2022-04-25 14:56
Closing due to, we cannot reproduce. 
Please open a new issue with a reference to this one if you can follow up with more information.

**Closed by kazupon** 2022-04-25 14:56 UTC
Labels: Status: Need More Info
